ab=input("Digite algo: ")
print("O tipo primitivo da variavel eh: ",type(ab))
print("Eh alfabetica ? ",ab.isalpha())
print("So tem espacos? ", ab.isspace())
print("Eh um numero ? ",ab.isnumeric())
print("Eh alphanumerico? ",ab.isalnum())
print("Esta toda em minuscula ? ",ab.islower())
print("Esta toda em maisculo ? ",ab.isupper())
print("Eh capitalizada ? ",ab.istitle())